name: CI/CD

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [22]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v5

    - name: Install Pnpm
      run: |
        npm install -g corepack@latest --force
        corepack enable

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Run unit tests
      run: pnpm test:unit

    - name: Run e2e tests
      run: pnpm test:e2e:setup && pnpm test:e2e
