name: CI/CD
on: [push, pull_request]
permissions:
  contents: read
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [22]
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    steps:
    - uses: actions/checkout@v4

    - name: Install Pnpm
      run: corepack enable

    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Run unit tests
      run: pnpm test:unit

    # TODO
    # - name: Run e2e tests
    #   run: pnpm test:e2e
